<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link rel="stylesheet" href="/styles.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="css/output.css" rel="stylesheet"> <!--tailwind-->
</head>
<body class="m-28 mt-80 text-center  bg-gradient-to-r from-teal-400 to-blue-500">
<h1 class="text-8xl font-mono">On my to-do list...</h1>
<form method="POST" action="/add"><br><br>
    <label for="taskLabel"> </label>
    <input placeholder="Add your task here..." class="placeholder:italic appearance-none border rounded-2xl
            bg-green-950 py-5 px-16 p-8 text-white leading-tight focus:outline-none
            focus:shadow-outline text-xl font-mono mr-6" type="text" name="taskLabel" id="taskLabel">
    <input class="bg-green-950 hover:bg-green-700 text-white font-bold py-4 px-7 rounded"
           type="submit" value="Add"></form>
<br> <br>
<?php
foreach ($tasks as $task) { ?>
    <div class="text-3xl font-mono">
        <span> <i class='bx bx-chevrons-right'></i>
    <?php echo $task['tasks']; ?>
        <form style='display: inline-block' method='POST' action='/markDone/
             <?php echo isset($task['id']) ? $task['id'] : ''; ?>'>
    <input class="bg-transparent hover:bg-green-600 text-green-950 font-semibold text-xl hover:text-white
             py-1 px-2 border border-blue-500 hover:border-transparent rounded" type='submit' value='✓'>
      </form>
        </span>
    </div>
    <?php
}
?>
<br> <br>
<a class="text-2xl border border-solid border-emerald-950 p-3" href="/completed">Show completed tasks</a>
</body>
</html>
